### ISSUE TITLE
Build requires login to docker hub

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria-react-ui#46]
On push of a dev branch to a managed fork (which is up to date with main branch) the build that is triggered apparently needs to log into dockerhub but does not have credentials.

**Comment by planetf1** [comment]
See build yaml in .github/workflows/node-build.yml

The intent was that this step should not execute on a fork 
```
- name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        if: ${{ github.event_name == 'push' }}
        ```
        
But this conditional actually only fixes the PR (not merge) build

Need to add an extra conditional...?

if: github.repository != ‘odpi/egeria-react-ui’
